/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-07-03 06:56:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ListadoRegistroProducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Registrar Nuevo Producto</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"c5dec5\">\r\n");
      out.write(" <h2 align=\"center\">Registrar Nuevo Producto</h2>\r\n");
      out.write("    <form action=\"ControladorProducto\" method=\"post\" style=\"margin: 20px auto; width: 50%; text-align: left;\">\r\n");
      out.write("        <label for=\"nombre\">Nombre:</label>\r\n");
      out.write("        <input type=\"text\" id=\"nombre\" name=\"nombre\" required><br>\r\n");
      out.write("        <label for=\"precio\">Precio Compra:</label>\r\n");
      out.write("        <input type=\"text\" id=\"precio\" name=\"precio\" required><br>\r\n");
      out.write("        <label for=\"precio_venta\">Precio Venta:</label>\r\n");
      out.write("        <input type=\"text\" id=\"precio_venta\" name=\"precio_venta\" required><br>\r\n");
      out.write("        <label for=\"estado\">Estado:</label>\r\n");
      out.write("        <input type=\"text\" id=\"estado\" name=\"estado\" required><br>\r\n");
      out.write("        <label for=\"descripcion\">Descripción:</label>\r\n");
      out.write("        <textarea id=\"descripcion\" name=\"descripcion\" required></textarea><br>\r\n");
      out.write("        <input type=\"submit\" value=\"Registrar\">\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    <hr>\r\n");
      out.write("    \r\n");
      out.write("    <h2 align=\"center\">Listado de Productos</h2>\r\n");
      out.write("    <table border=\"1\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>ID</th>\r\n");
      out.write("                <th>Nombre</th>\r\n");
      out.write("                <th>Precio Compra</th>\r\n");
      out.write("                <th>Precio Venta</th>\r\n");
      out.write("                <th>Estado</th>\r\n");
      out.write("                <th>Descripción</th>\r\n");
      out.write("                <th>Acciones</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("            <c:forEach var=\"producto\" items=\"${listadodeproductos}\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>${producto.idproductocl3}</td>\r\n");
      out.write("                    <td>${producto.nombrecl3}</td>\r\n");
      out.write("                    <td>${producto.preciocompracl3}</td>\r\n");
      out.write("                    <td>${producto.precioventacl3}</td>\r\n");
      out.write("                    <td>${producto.estadocl3}</td>\r\n");
      out.write("                    <td>${producto.descripcl3}</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <a href=\"ControladorProducto?accion=Modificar&cod=${producto.idproductocl3}\">Modificar</a>\r\n");
      out.write("                        <!-- Puedes agregar más acciones aquí -->\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </c:forEach>\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
